name       : libansilove
version    : 1.2.9
release    : 6
source     :
    - https://github.com/ansilove/libansilove/archive/refs/tags/1.2.9.tar.gz : 88057f7753bf316f9a09ed15721b9f867ad9f5654c0b49af794d8d98b9020a66
homepage   : https://www.ansilove.org
license    : BSD-2-Clause
component  : programming.library
summary    : Library for converting ANSI, ASCII, and other formats to PNG
description: |
    libansilove is a library to convert ANSi and artscene related file formats into PNG images.
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
