name       : libansilove
version    : 1.4.1
release    : 8
source     :
    - https://github.com/ansilove/libansilove/archive/refs/tags/1.4.1.tar.gz : c6aa32bcef54b05b9af535c621f7044156295a49cea3cfaf1c868e359be59203
homepage   : https://www.ansilove.org
license    : BSD-2-Clause
component  : programming.library
summary    : Library for converting ANSI, ASCII, and other formats to PNG
description: |
    libansilove is a library to convert ANSi and artscene related file formats into PNG images.
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove static library
    rm -rf $installdir/%libdir%/libansilove-static.a
