name       : libansilove
version    : 1.1.2
release    : 1
source     :
    - https://github.com/ansilove/libansilove/releases/download/1.1.2/libansilove-1.1.2.tar.gz : 0c8c1402c746249df233c66c1fd4c467515490aa3cfc4c26f8f181b6a2060a2c
license    : BSD-2-Clause
component  : programming.library
summary    : Library for converting ANSI, ASCII, and other formats to PNG
description: |
    Library for converting ANSI, ASCII, and other formats to PNG
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
