name       : libansilove
version    : 1.1.5
release    : 2
source     :
    - https://github.com/ansilove/libansilove/archive/1.1.5.tar.gz : 05fc6d36265dd3aa6c79c0b299df2856493c712ac0f36399b4b823b6388f40f9
homepage   : https://www.ansilove.org
license    : BSD-2-Clause
component  : programming.library
summary    : Library for converting ANSI, ASCII, and other formats to PNG
description: |
    libansilove is a library to convert ANSi and artscene related file formats into PNG images.
builddeps  :
    - pkgconfig(gdlib)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
